package net.runelite.client.plugins.arcer;

public enum ARcerState
{
	ANIMATING,
	MOVING,
	TIMEOUT,
	BANK_NOT_FOUND,
	FIND_BANK,
	DEPOSIT_ITEMS,
	HANDLE_BREAK,
	USE_SHORTCUT,
	DRINKING_STAM,
	WITHDRAW_STAM,
	DEPOSIT_INVENT,
	WITHDRAW_RING,
	MINE_ESSENCE,
	WALK_TO_MAGE,
	CRAFT_TIARAS,
	ENTER_ALTAR,
	CRAFT_RUNES,
	USE_PORTAL,
	WALK_FIRST_POINT,
	WALK_SECOND_POINT,
	WALK_THIRD_POINT,
	WALK_NEARER_ALTER,
	WITHDRAW_ITEMS,
	UNHANDLED_STATE;
}
